# Generated by Django 6.1 on 2026-08-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='order',
            field=models.PositiveIntegerField(help_text='Порядковый номер для сортировки'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_through', to='employees.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1–10'),
        ),
    ]
