# Generated by Django 6.0.7 on 2026-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рабочего места')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
