# Generated by Django 6.0.7 on 2026-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workplace_delete_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='desk_number',
            field=models.CharField(max_length=20, verbose_name='Номер рабочего места'),
        ),
    ]
